CREATE TABLE [Staging].[CurrentArchivedHourlyData] (
    [CityID]            INT            NULL,
    [CityName]          NVARCHAR (60)  NULL,
    [Latitude]          NVARCHAR (16)  NULL,
    [Longitude]         NVARCHAR (16)  NULL,
    [CountryCode]       NVARCHAR (2)   NULL,
    [TimeZone]          NVARCHAR (16)  NULL,
    [Sunrise]           INT            NULL,
    [Sunset]            INT            NULL,
    [Code]              INT            NULL,
    [WeatherID]         INT            NULL,
    [WeatherMain]       NVARCHAR (60)  NULL,
    [WeatherDesc]       NVARCHAR (100) NULL,
    [WeatherIcon]       NVARCHAR (10)  NULL,
    [TempInC]           DECIMAL (5, 2) NULL,
    [Pressure]          SMALLINT       NULL,
    [Humidity]          DECIMAL (5, 2) NULL,
    [Temp_Min_C]        DECIMAL (5, 2) NULL,
    [Temp_Max_C]        DECIMAL (5, 2) NULL,
    [Visibility]        INT            NULL,
    [WindSpeed]         NVARCHAR (6)   NULL,
    [WindDeg]           DECIMAL (6, 3) NULL,
    [Rain3H]            NVARCHAR (10)  NULL,
    [Cloudniess]        SMALLINT       NULL,
    [Base]              NVARCHAR (16)  NULL,
    [SysType]           NVARCHAR (10)  NULL,
    [SysID]             INT            NULL,
    [SysMessage]        NVARCHAR (60)  NULL,
    [CalulatedDateTime] INT            NULL,
    [InsertedTimeStamp] DATETIME       NULL
);

